export const ACTION_INCREMENT_COUNTER = 'counter/ACTION_INCREMENT_COUNTER';
export const ACTION_DECREMENT_COUNTER = 'counter/ACTION_DECREMENT_COUNTER';
export const ACTION_INCREMENT_COUNTER_ASYNC = 'counter/ACTION_INCREMENT_COUNTER_ASYNC';
