export const ACTION_LOAD_PLACES = 'places/ACTION_LOAD_PLACES';
export const ACTION_CREATE_PLACE = 'places/ACTION_CREATE_PLACE';
export const ACTION_UPDATE_PLACE = 'places/ACTION_UPDATE_PLACE';
export const ACTION_GET_PLACE = 'places/ACTION_GET_PLACE';
export const ACTION_DELETE_PLACE = 'places/ACTION_DELETE_PLACE';
